### ISSUE TITLE
Error converting

### ISSUE THREAD

**Issue by happynoodle** [adaptivethreat/BloodHound#35]
I'm using the command "Get-BloodHoundData | Export-BloodHoundCSV -CSVFolder C:\BloodHoundData\" after importing the modules/cmdlets from the BloodHound powershell script.

I'm receiving back a TON of the following error. There are different SIDs everytime but they are all SIDs.

WARNING: Error converting CN=SID,CN=redacted,DC=redacted,DC=redacted,DC=redacted

I'm not sure what I can do to resolve this issue. I also attempted to utilize: 

Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:7474/ -UserPass "neo4j:BloodHound"

but I get a error connecting to the server. 

Error connecting to Neo4j rest REST server at 'http://localhost:7474/'
At C:\Bloodhound\PowerShell\BloodHound.ps1:13849 char:13
+             throw "Error connecting to Neo4j rest REST server at '$($URI.Absolut ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error connectin...ocalhost:7474/':String) [], RuntimeException
    + FullyQualifiedErrorId : Error connecting to Neo4j rest REST server at 'http://localhost:7474/'

My collector and my database server are local to the same machine. Please provide some input, I would be happy to troubleshoot, but I really am unsure of where to begin.

Thanks for the wonderful tool! If only I could get it working.

**Comment by derekhillhp** [comment]
DId you change the password on the neo4j server by browsing to the IP:Port. I was missing this step before and until I did that nothing worked.

**Comment by rvazarkar** [comment]
If this is a new database, make sure you change the password before doing anything else. By default, you can do it by logging into the neo4j interface in your browser at localhost:7474 and changing the database password.

The default creds for a new database is neo4j:neo4j

As for the warnings, warnings are not critical, frequently SIDs cant be converted. You can go ahead and ignore them, you should still get meaningful data.

I'm going to go ahead and close this for now, feel free to re-open it if you need to. Otherwise, you can also hit us up on the BloodHound Slack Channel
